version: 0.2

env:
  variables:
    app_name: "cicd-tests"
  parameter-store:
    DOCKER_REGISTRY_USERNAME: /docker-creds/username
    DOCKER_REGISTRY_PASSWORD: /docker-creds/password
    DOCKER_REGISTRY_URL: /docker-registry/url
phases:
  install:
    runtime-versions:
      python: 3.12
  pre_build:
    commands:
      - echo "Installing dependencies..."
      - pip install -r requirements.txt
      - pip install flake8
  build:
    commands:
      - echo "Running linter..."
      - flake8 app.py
      - flake8 tests/unit_test_app.py
      - echo "Running tests..."
      - python -m unittest tests/unit_test_app.py
      - echo "Building Docker image..."
      - echo "$DOCKER_REGISTRY_PASSWORD" | docker login --username "$DOCKER_REGISTRY_USERNAME" --password-stdin
      - docker build -t "$DOCKER_REGISTRY_USERNAME/${app_name}:latest" .
      - docker push "$DOCKER_REGISTRY_USERNAME/${app_name}:latest"
  post_build:
    commands:
      - echo "Build completed successfully!"
artifacts:
  files:
    - '**/*'