AWSTemplateFormatVersion: '2010-09-09'
Description: 'CloudFormation template for CodeBuild project with GitHub source'

Parameters:
  GitHubOwner:
    Type: String
    Description: GitHub repository owner
    Default: lroquec
  GitHubRepo:
    Type: String
    Description: GitHub repository name
    Default: aws-codepipeline
  GitHubBranch:
    Type: String
    Description: GitHub branch name
    Default: main
  GitHubTokenParameterName:
    Type: String
    Description: Name of the SSM Parameter Store parameter containing the GitHub token
    Default: "/git/token"
  GitHubConnectionArn:
    Type: String
    Description: ARN from CodeStar con GitHub
    Default: "arn:aws:codeconnections:us-east-1:010526263844:connection/995c028e-b20b-4edf-a2c2-9b565d807773"

Resources:
  CodeBuildProject:
    Type: AWS::CodeBuild::Project
    Properties:
      Name: !Sub ${AWS::StackName}-project
      Description: CodeBuild project with GitHub source
      ServiceRole: !GetAtt CodeBuildServiceRole.Arn
      Artifacts:
        Type: NO_ARTIFACTS
      Environment:
        Type: LINUX_CONTAINER
        ComputeType: BUILD_GENERAL1_SMALL
        Image: aws/codebuild/amazonlinux2-x86_64-standard:5.0
      Source:
        Type: GITHUB
        Auth: 
          Type: CODECONNECTIONS
          Resource: !Ref GitHubConnectionArn
        Location: !Sub https://github.com/${GitHubOwner}/${GitHubRepo}.git
        GitCloneDepth: 1
        GitSubmodulesConfig:
          FetchSubmodules: false
        BuildSpec: buildspec.yaml
      SourceVersion: !Ref GitHubBranch

  CodeBuildServiceRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: codebuild.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AWSCodeBuildAdminAccess
      Policies:
        - PolicyName: CodeBuildServiceRolePolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource: '*'
              - Effect: Allow
                Action:
                  - s3:GetBucketLocation
                  - s3:ListAllMyBuckets
                  - s3:GetObject
                  - s3:GetObjectVersion
                  - s3:PutObject
                Resource: '*'
              - Effect: Allow
                Action:
                  - ssm:GetParameter
                  - ssm:GetParameters
                Resource: !Sub arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter/*
              - Effect: Allow
                Action:
                  - codestar-connections:*
                Resource: !Ref GitHubConnectionArn

Outputs:
  CodeBuildProjectName:
    Description: Name of the CodeBuild project
    Value: !Ref CodeBuildProject
  CodeBuildProjectArn:
    Description: ARN of the CodeBuild project
    Value: !GetAtt CodeBuildProject.Arn